# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dobrik4ever/Library/CloudStorage/OneDrive-Personal/Documents/Study/winter_21-22/Master Thesis/3 Methods, material/src/GUI/flatten_stack.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1132, 447)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sliders_groupBox = QtWidgets.QGroupBox(Form)
        self.sliders_groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sliders_groupBox.setObjectName("sliders_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sliders_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.sliders_groupBox)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slider_depth_selector = QtWidgets.QSlider(self.groupBox)
        self.slider_depth_selector.setOrientation(QtCore.Qt.Vertical)
        self.slider_depth_selector.setInvertedAppearance(True)
        self.slider_depth_selector.setObjectName("slider_depth_selector")
        self.horizontalLayout_2.addWidget(self.slider_depth_selector)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_image_sideview = QtWidgets.QLabel(self.groupBox)
        self.label_image_sideview.setScaledContents(True)
        self.label_image_sideview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_sideview.setObjectName("label_image_sideview")
        self.verticalLayout_4.addWidget(self.label_image_sideview)
        self.slider_slice_selector = QtWidgets.QSlider(self.groupBox)
        self.slider_slice_selector.setOrientation(QtCore.Qt.Horizontal)
        self.slider_slice_selector.setObjectName("slider_slice_selector")
        self.verticalLayout_4.addWidget(self.slider_slice_selector)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox_channel_selector = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_channel_selector.setMinimum(0)
        self.spinBox_channel_selector.setMaximum(2)
        self.spinBox_channel_selector.setProperty("value", 0)
        self.spinBox_channel_selector.setObjectName("spinBox_channel_selector")
        self.horizontalLayout_3.addWidget(self.spinBox_channel_selector)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.sliders_groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.slider_slices_average = QtWidgets.QSlider(self.groupBox_2)
        self.slider_slices_average.setMinimum(1)
        self.slider_slices_average.setMaximum(10)
        self.slider_slices_average.setOrientation(QtCore.Qt.Horizontal)
        self.slider_slices_average.setObjectName("slider_slices_average")
        self.horizontalLayout_4.addWidget(self.slider_slices_average)
        self.slices_average_Slider_label = QtWidgets.QLabel(self.groupBox_2)
        self.slices_average_Slider_label.setObjectName("slices_average_Slider_label")
        self.horizontalLayout_4.addWidget(self.slices_average_Slider_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.radioButton_nofiltering = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_nofiltering.setChecked(True)
        self.radioButton_nofiltering.setObjectName("radioButton_nofiltering")
        self.verticalLayout_3.addWidget(self.radioButton_nofiltering)
        self.radioButton_median_filtering = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_median_filtering.setChecked(False)
        self.radioButton_median_filtering.setObjectName("radioButton_median_filtering")
        self.verticalLayout_3.addWidget(self.radioButton_median_filtering)
        self.radioButton_average_filtering = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_average_filtering.setChecked(False)
        self.radioButton_average_filtering.setObjectName("radioButton_average_filtering")
        self.verticalLayout_3.addWidget(self.radioButton_average_filtering)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.sliders_groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.sliders_groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_image_initial = QtWidgets.QLabel(self.groupBox_3)
        self.label_image_initial.setScaledContents(True)
        self.label_image_initial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_initial.setObjectName("label_image_initial")
        self.horizontalLayout_6.addWidget(self.label_image_initial)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.Image_groupBox = QtWidgets.QGroupBox(Form)
        self.Image_groupBox.setObjectName("Image_groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Image_groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_image_processed = QtWidgets.QLabel(self.Image_groupBox)
        self.label_image_processed.setScaledContents(True)
        self.label_image_processed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_processed.setObjectName("label_image_processed")
        self.horizontalLayout_5.addWidget(self.label_image_processed)
        self.horizontalLayout.addWidget(self.Image_groupBox)

        self.retranslateUi(Form)
        self.slider_slices_average.valueChanged['int'].connect(self.slices_average_Slider_label.setNum)
        self.slider_depth_selector.valueChanged['int'].connect(self.label_2.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sliders_groupBox.setTitle(_translate("Form", "Tools"))
        self.groupBox.setTitle(_translate("Form", "Depth slicing"))
        self.label_image_sideview.setText(_translate("Form", "IMAGE"))
        self.label_2.setText(_translate("Form", "Slice: 0"))
        self.label.setText(_translate("Form", "Channel"))
        self.groupBox_2.setTitle(_translate("Form", "Depth filtering"))
        self.label_3.setText(_translate("Form", "N slices to filter"))
        self.slices_average_Slider_label.setText(_translate("Form", "1"))
        self.radioButton_nofiltering.setText(_translate("Form", "None"))
        self.radioButton_median_filtering.setText(_translate("Form", "Median"))
        self.radioButton_average_filtering.setText(_translate("Form", "Average"))
        self.pushButton.setText(_translate("Form", "Ok"))
        self.groupBox_3.setTitle(_translate("Form", "MAX Image before processing"))
        self.label_image_initial.setText(_translate("Form", "IMAGE"))
        self.Image_groupBox.setTitle(_translate("Form", "MAX Image after processing"))
        self.label_image_processed.setText(_translate("Form", "IMAGE"))

